-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/growthexperiments_link_submissions.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE growthexperiments_link_submissions (
  gels_revision INT NOT NULL,
  gels_anchor_offset INT NOT NULL,
  gels_target INT NOT NULL,
  gels_page INT NOT NULL,
  gels_edit_revision INT DEFAULT NULL,
  gels_user INT NOT NULL,
  gels_anchor_length INT NOT NULL,
  gels_feedback VARCHAR(1) NOT NULL,
  PRIMARY KEY(
    gels_revision, gels_target, gels_anchor_offset
  )
);

CREATE INDEX gels_page_feedback_target ON growthexperiments_link_submissions (
  gels_page, gels_feedback, gels_target
);
