-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/growthexperiments_mentee_data.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE growthexperiments_mentee_data (
  mentee_id INT NOT NULL,
  mentee_data TEXT DEFAULT '{}' NOT NULL,
  PRIMARY KEY(mentee_id)
);
