var TOPIC_MATCH_MODE_OR = 'OR';
var TOPIC_MATCH_MODE_AND = 'AND';
var TOPIC_MATCH_MODES = {
	OR: TOPIC_MATCH_MODE_OR,
	AND: TOPIC_MATCH_MODE_AND
};

module.exports = {
	TOPIC_MATCH_MODES: TOPIC_MATCH_MODES
};
