module.exports = {
	DMRecommendedLinkAnnotation: require( './addlink/dmRecommendedLinkAnnotation.js' ),
	CERecommendedLinkAnnotation: require( './addlink/ceRecommendedLinkAnnotation.js' ),
	DMRecommendedLinkErrorAnnotation: require( './addlink/dmRecommendedLinkErrorAnnotation.js' ),
	CERecommendedLinkErrorAnnotation: require( './addlink/ceRecommendedLinkErrorAnnotation.js' ),
	RecommendedLinkRejectionDialog: require( './addlink/RecommendedLinkRejectionDialog.js' ),
	AddLinkArticleTarget: require( './addlink/AddLinkArticleTarget.js' ),
	LinkSuggestionInteractionLogger: require( './addlink/LinkSuggestionInteractionLogger.js' ),
	AddLinkSaveDialog: require( './addlink/AddLinkSaveDialog.js' ),
	RecommendedLinkToolbarDialog: require( './addlink/RecommendedLinkToolbarDialog.js' ),
	AddLinkTargetInitializer: require( './addlink/AddLinkTargetInitializer.js' ),
	AddImageTargetInitializer: require( './addimage/AddImageTargetInitializer.js' ),
	AddImageArticleTarget: require( './addimage/AddImageArticleTarget.js' ),
	StructuredTaskArticleTarget: require( './StructuredTaskArticleTarget.js' ),
	StructuredTaskSaveDialog: require( './StructuredTaskSaveDialog.js' ),
	MachineSuggestionsMode: require( './MachineSuggestionsMode.js' ),
	EditModeMachineSuggestions: require( './EditModeMachineSuggestions.js' ),
	EditModeVisualWithSuggestions: require( './EditModeVisualWithSuggestions.js' ),
	SuggestionsArticleTarget: require( './SuggestionsArticleTarget.js' ),
	EditModeConfirmationDialog: require( './EditModeConfirmationDialog.js' )
};
