<?php

declare( strict_types = 1 );

namespace GrowthExperiments\NewcomerTasks\TaskType;

use GrowthExperiments\NewcomerTasks\RecommendationProvider;
use GrowthExperiments\NewcomerTasks\SubmissionHandler;
use MessageLocalizer;
use Wikimedia\Message\MessageSpecifier;

/**
 * TaskTypeHandler subclass for structured tasks. Instead of freeform editing, structured tasks
 * offer the user to apply a recommendation (typically generated by some machine learning system)
 * to the article.
 * @see https://www.mediawiki.org/wiki/Growth/Personalized_first_day/Structured_tasks
 */
abstract class StructuredTaskTypeHandler extends TaskTypeHandler {

	/**
	 * Returns the provider which can be used to fetch a recommendation for a given page.
	 * @return RecommendationProvider
	 */
	abstract public function getRecommendationProvider(): RecommendationProvider;

	/**
	 * Returns the handler which can be used to process a user submission (such as a user
	 * accepting or rejecting a recommendation).
	 * @return SubmissionHandler
	 */
	abstract public function getSubmissionHandler(): SubmissionHandler;

	/**
	 * Returns a message describing the format of the acceptance/rejectance data that needs to
	 * be provided in some APIs. Should use API documentation conventions.
	 * @param TaskType $taskType
	 * @param MessageLocalizer $localizer
	 * @return MessageSpecifier
	 */
	abstract public function getSubmitDataFormatMessage(
		TaskType $taskType,
		MessageLocalizer $localizer
	): MessageSpecifier;

}
