-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/growthexperiments_link_recommendations.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/growthexperiments_link_recommendations (
  gelr_revision INTEGER UNSIGNED NOT NULL,
  gelr_page INTEGER UNSIGNED NOT NULL,
  gelr_data BLOB NOT NULL,
  PRIMARY KEY(gelr_revision)
);

CREATE INDEX gelr_page ON /*_*/growthexperiments_link_recommendations (gelr_page);
