-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/growthexperiments_link_submissions.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/growthexperiments_link_submissions (
  gels_revision INTEGER UNSIGNED NOT NULL,
  gels_anchor_offset INTEGER UNSIGNED NOT NULL,
  gels_target INTEGER UNSIGNED NOT NULL,
  gels_page INTEGER UNSIGNED NOT NULL,
  gels_edit_revision INTEGER UNSIGNED DEFAULT NULL,
  gels_user INTEGER UNSIGNED NOT NULL,
  gels_anchor_length INTEGER UNSIGNED NOT NULL,
  gels_feedback VARCHAR(1) NOT NULL,
  PRIMARY KEY(
    gels_revision, gels_target, gels_anchor_offset
  )
);

CREATE INDEX gels_page_feedback_target ON /*_*/growthexperiments_link_submissions (
  gels_page, gels_feedback, gels_target
);
