-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/growthexperiments_mentor_mentee.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/growthexperiments_mentor_mentee (
  gemm_mentee_id INT UNSIGNED NOT NULL,
  gemm_mentor_role VARBINARY(255) NOT NULL,
  gemm_mentor_id INT UNSIGNED NOT NULL,
  gemm_mentee_is_active TINYINT DEFAULT 1 NOT NULL,
  INDEX gemm_mentor (
    gemm_mentor_id, gemm_mentee_is_active
  ),
  PRIMARY KEY(
    gemm_mentee_id, gemm_mentor_role
  )
) /*$wgDBTableOptions*/;
