-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/growthexperiments_link_recommendations.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/growthexperiments_link_recommendations (
  gelr_revision INT UNSIGNED NOT NULL,
  gelr_page INT UNSIGNED NOT NULL,
  gelr_data MEDIUMBLOB DEFAULT NULL,
  INDEX gelr_page (gelr_page),
  PRIMARY KEY(gelr_revision)
) /*$wgDBTableOptions*/;
