-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/growthexperiments_link_submissions.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/growthexperiments_link_submissions (
  gels_revision INT UNSIGNED NOT NULL,
  gels_anchor_offset INT UNSIGNED NOT NULL,
  gels_target INT UNSIGNED NOT NULL,
  gels_page INT UNSIGNED NOT NULL,
  gels_edit_revision INT UNSIGNED DEFAULT NULL,
  gels_user INT UNSIGNED NOT NULL,
  gels_anchor_length INT UNSIGNED NOT NULL,
  gels_feedback VARCHAR(1) NOT NULL,
  INDEX gels_page_feedback_target (
    gels_page, gels_feedback, gels_target
  ),
  PRIMARY KEY(
    gels_revision, gels_target, gels_anchor_offset
  )
) /*$wgDBTableOptions*/;
